### ISSUE TITLE
Kornia integration

### ISSUE THREAD

**Issue by edgarriba** [TheZino/PlanckianJitter#2]
Hi @TheZino , we were planning to add your paper implementation in Kornia. Are you open to help with that ? /cc @ducha-aiki @shijianjian

**Comment by nrupatunga** [comment]
@edgarriba I'm interested and would love to work on any integration aspect of this functionality.

**Comment by edgarriba** [comment]
@nrupatunga created a ticket in kornia -- the implementation should be quite straigh forward using our base augmentations api

**Comment by TheZino** [comment]
Hello @edgarriba, sorry for the late answer.
Thank you for writing to me.

Yes it would be nice to contribute in the integration of the PlanckianJitter in your library.
